### PR TITLE
[FIX] :Tapping once on the board doesn't draw. #1

### PR DESCRIPTION
**Pull request by siddharthmagadum16**
### Fixes
This PR is followup of the previous PR(#3), this resolves issue #1

### CODE REVIEW

**Comment by siddharthmagadum16** [comment]
@harshhhdev  Can you please review this PR?

**Comment by harshhhdev** [comment]
> @harshhhdev Can you please review this PR?

Yep, just tested it out & it looks good. I'll merge it in & run my Prettier formatting on it by myself.

**Comment by siddharthmagadum16** [comment]
@harshhhdev hey, can you add the hacktoberfest-accepted label for both my PR's?  I didn't notice that this repo is not participating in hacktoberfest.

**Comment by harshhhdev** [comment]
> @harshhhdev hey, can you add the hacktoberfest-accepted label for both my PR's? I didn't notice that this repo is not participating in hacktoberfest.

Whoops sorry. I'll add the Hacktoberfest topic to this PR.

**Pull request merged**
